version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GITTEST_1006Project
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_gittest_1006.integrations:GitSyncFlow
  packages:
  - name: SIQA_GITTEST_1006Project
    version: "1.0"
