version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GITTEST_1006Project
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_gittest_1006.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GITTEST_1006Project
    version: "1.0"
- serviceName: project.siqa_gittest_1006.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GITTEST_1006Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: project.siqa_gittest_1006.integrations:GitSyncFlow
  packages:
  - name: SIQA_GITTEST_1006Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: project.siqa_gittest_1006.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GITTEST_1006Project
    version: "1.0"
- serviceName: project.siqa_gittest_1006.integrations:deepclonetest
  packages:
  - name: SIQA_GITTEST_1006Project
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
